apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  # namespace: devns
spec: # ServiceSpec
  type: NodePort
  selector: # Route service traffic to pods with label keys and values matching this selector.
    app: nginx
  ports: # List of ports exposed by this service
  - port: 80 # The port that will be exposed by this service
    targetPort: nginx-pod-port # Number or name of the port to access on the pods targeted by the service
    nodePort: 30000 # port on each node on which this service is exposed
