apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  # namespace: devns
spec: # PodSpec
  containers:
  - name: test-container
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    volumeMounts: # Pod volumes to mount into the container's filesystem
      - mountPath: /cache
        name: cache-volume # This must match the Name of a Volume
  volumes: # List of volumes that can be mounted by containers belonging to the pod
    - name: cache-volume
      emptyDir: {}
        
