apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  # namespace: devns
spec:
  containers:
  - name: test-container
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    volumeMounts:
      - mountPath: /myappdata
        name: myvol-hostpath
  volumes:
    - name: myvol-hostpath
      hostPath: # directory location on host
          # For minikube, hostPath refers to the path inside the minikube vm.
          # minikube creates a vm and then runs your containers on it.
          # Run 'minikube ssh' to connect to the minikube vm.
          # You can also use 'minikube mount sourcedir:targetdir' to mount actual host dir
        path: /home/docker/mydata      
