apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data: # Store secret data in base64. E.g. admin, mypassword
  username: YWRtaW4=
  password: bXlwYXNzd29yZA==
---

# Define container environment variables using Secret data. 
# Ref: https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure/#define-container-environment-variables-using-secret-data
# Secret must be created before pod that uses the secret can be created.
# If you try to create a pod without first creating the secret, you'll get this error.
# CreateContainerConfigError Error: secret "SECRET_NAME" not found
# Go into the pod: k exec -it secret-pod -- bash
# Run 'echo $USERNAME $PASSWORD $MY_ENV_VAR_NAME'. You'll get values of the env variables: 'admin mypassword MY_ENV_VAR_VALUE'

apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  containers:
  - name: mycontainer
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    env: # List of environment variables to set in the container
      - name: USERNAME # Name of the environment variable
        valueFrom: # Source for the environment variable's value
          secretKeyRef: # Selects a key of a secret in the pod's namespace
            name: mysecret
            key: username
      - name: PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: password
      - name: MY_ENV_VAR_NAME # static env variable
        value: MY_ENV_VAR_VALUE
