apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data: # Store secret data in base64. E.g. admin, mypassword
  username: YWRtaW4=
  password: bXlwYXNzd29yZA==
---

apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  containers:
  - name: mycontainer
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    envFrom: # List of sources to populate environment variables in the container
      - secretRef: # The Secret to select from
          name: mysecret
