apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data: # Store secret data in base64. E.g. admin, mypassword
  username: YWRtaW4=
  password: bXlwYXNzd29yZA==
---

# Create a Pod that has access to the secret data through a Volume
# https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure/
apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  containers:
  - name: mycontainer
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
      - mountPath: /mymnt/secret-volume
        name: secret-volume # name must match the volume name below
        readOnly: true
  # The secret data is exposed to Containers in the Pod through a Volume.
  volumes:
    - name: secret-volume
      secret:
        secretName: mysecret
        optional: true
