apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
  - name: busybox-container
    image: busybox
    command: ["/bin/sh"]
    args: ["-c", "date; echo sleeping..; sleep 10s; echo exiting..; date"]
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
